// Generated by scripts/gen-examples.mjs — do not edit by hand.
// Pre-computed EXPLAIN QUERY PLAN FORMAT=JSON output for the demo
// schema in scripts/demo-schema.sql, so the tool can demo itself
// without a database.
window.PLAN_EXAMPLES = [
 {
  "name": "Kitchen sink: CTE + EXISTS + subqueries + group/sort",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON WITH big_spenders AS (\n  SELECT user_id, sum(amount) AS total\n  FROM orders GROUP BY user_id\n)\nSELECT c.name, count(*) AS n\nFROM users u\nJOIN cities c ON c.id = u.city_id\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE u.age IN (SELECT age FROM users WHERE city_id = 3)\n  AND EXISTS (SELECT 1 FROM big_spenders s WHERE s.user_id = u.id)\n  AND u.id > (SELECT avg(user_id) FROM big_spenders)\nGROUP BY c.name\nORDER BY n DESC;",
   "result_columns": [
    "name",
    "n"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "LIST SUBQUERY 1",
     "op": {
      "type": "list_subquery",
      "subquery_id": 1,
      "correlated": false
     }
    },
    {
     "id": 4,
     "parent": 1,
     "detail": "SCAN users",
     "op": {
      "type": "scan",
      "table": "users",
      "source": "table"
     }
    },
    {
     "id": 13,
     "parent": null,
     "detail": "SCALAR SUBQUERY 2",
     "op": {
      "type": "scalar_subquery",
      "subquery_id": 2,
      "correlated": false
     }
    },
    {
     "id": 17,
     "parent": 13,
     "detail": "SCAN big_spenders",
     "op": {
      "type": "scan",
      "table": "big_spenders",
      "subquery": {
       "execution": "coroutine",
       "cte_id": 0
      },
      "source": "subquery"
     }
    },
    {
     "id": 19,
     "parent": 17,
     "detail": "SCAN orders USING INDEX idx_orders_user",
     "op": {
      "type": "scan",
      "table": "orders",
      "source": "table",
      "index": {
       "name": "idx_orders_user",
       "covering": false,
       "ephemeral": false
      }
     }
    },
    {
     "id": 69,
     "parent": null,
     "detail": "SEARCH u USING INTEGER PRIMARY KEY (rowid=?)",
     "op": {
      "type": "search",
      "table": "users",
      "alias": "u",
      "search_kind": "seek",
      "integer_primary_key": true,
      "constraints": [
       "rowid=?"
      ]
     }
    },
    {
     "id": 70,
     "parent": null,
     "detail": "SEARCH c USING COVERING INDEX ephemeral_cities_t4 (id=?)",
     "op": {
      "type": "search",
      "table": "cities",
      "alias": "c",
      "join": "inner",
      "search_kind": "seek",
      "index": {
       "name": "ephemeral_cities_t4",
       "covering": true,
       "ephemeral": true
      },
      "constraints": [
       "id=?"
      ]
     }
    },
    {
     "id": 71,
     "parent": null,
     "detail": "SEARCH o USING COVERING INDEX idx_orders_user (user_id=?) LEFT-JOIN",
     "op": {
      "type": "search",
      "table": "orders",
      "alias": "o",
      "join": "left",
      "search_kind": "seek",
      "index": {
       "name": "idx_orders_user",
       "covering": true,
       "ephemeral": false
      },
      "constraints": [
       "user_id=?"
      ]
     }
    },
    {
     "id": 75,
     "parent": null,
     "detail": "USE SORTER FOR GROUP BY",
     "op": {
      "type": "group_by",
      "method": "sorter"
     }
    },
    {
     "id": 87,
     "parent": null,
     "detail": "SEARCH s USING INDEX ephemeral_subquery_t10 (user_id=?)",
     "op": {
      "type": "search",
      "table": "big_spenders",
      "alias": "s",
      "subquery": {
       "execution": "indexed_materialized",
       "cte_id": 0
      },
      "search_kind": "seek",
      "index": {
       "name": "ephemeral_subquery_t10",
       "covering": false,
       "ephemeral": true
      },
      "constraints": [
       "user_id=?"
      ]
     }
    },
    {
     "id": 90,
     "parent": 87,
     "detail": "SCAN orders USING INDEX idx_orders_user",
     "op": {
      "type": "scan",
      "table": "orders",
      "source": "table",
      "index": {
       "name": "idx_orders_user",
       "covering": false,
       "ephemeral": false
      }
     }
    },
    {
     "id": 219,
     "parent": null,
     "detail": "USE SORTER FOR ORDER BY",
     "op": {
      "type": "order_by",
      "method": "sorter"
     }
    }
   ]
  }
 },
 {
  "name": "Index search + left join + sort",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON SELECT u.name, o.amount\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE u.age > 21\nORDER BY o.amount DESC;",
   "result_columns": [
    "name",
    "amount"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "SEARCH u USING INDEX idx_users_age (age>?)",
     "op": {
      "type": "search",
      "table": "users",
      "alias": "u",
      "search_kind": "seek",
      "index": {
       "name": "idx_users_age",
       "covering": false,
       "ephemeral": false
      },
      "constraints": [
       "age>?"
      ]
     }
    },
    {
     "id": 2,
     "parent": null,
     "detail": "SEARCH o USING INDEX idx_orders_user (user_id=?) LEFT-JOIN",
     "op": {
      "type": "search",
      "table": "orders",
      "alias": "o",
      "join": "left",
      "search_kind": "seek",
      "index": {
       "name": "idx_orders_user",
       "covering": false,
       "ephemeral": false
      },
      "constraints": [
       "user_id=?"
      ]
     }
    },
    {
     "id": 28,
     "parent": null,
     "detail": "USE SORTER FOR ORDER BY",
     "op": {
      "type": "order_by",
      "method": "sorter"
     }
    }
   ]
  }
 },
 {
  "name": "Shared CTE used twice",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON WITH spenders AS (\n  SELECT user_id, sum(amount) AS total\n  FROM orders GROUP BY user_id\n)\nSELECT u.name, s1.total\nFROM users u\nJOIN spenders s1 ON s1.user_id = u.id\nJOIN spenders s2 ON s2.user_id = u.city_id;",
   "result_columns": [
    "name",
    "total"
   ],
   "nodes": [
    {
     "id": 2,
     "parent": null,
     "detail": "SCAN orders USING INDEX idx_orders_user",
     "op": {
      "type": "scan",
      "table": "orders",
      "source": "table",
      "index": {
       "name": "idx_orders_user",
       "covering": false,
       "ephemeral": false
      }
     }
    },
    {
     "id": 41,
     "parent": null,
     "detail": "SCAN users AS u",
     "op": {
      "type": "scan",
      "table": "users",
      "alias": "u",
      "source": "table"
     }
    },
    {
     "id": 42,
     "parent": null,
     "detail": "SEARCH s1 USING INDEX ephemeral_subquery_t3 (user_id=?)",
     "op": {
      "type": "search",
      "table": "spenders",
      "alias": "s1",
      "join": "inner",
      "subquery": {
       "execution": "materialized_reuse",
       "cte_id": 0
      },
      "search_kind": "seek",
      "index": {
       "name": "ephemeral_subquery_t3",
       "covering": false,
       "ephemeral": true
      },
      "constraints": [
       "user_id=?"
      ]
     }
    },
    {
     "id": 43,
     "parent": null,
     "detail": "SEARCH s2 USING INDEX ephemeral_subquery_t5 (user_id=?)",
     "op": {
      "type": "search",
      "table": "spenders",
      "alias": "s2",
      "join": "inner",
      "subquery": {
       "execution": "materialized_reuse",
       "cte_id": 0
      },
      "search_kind": "seek",
      "index": {
       "name": "ephemeral_subquery_t5",
       "covering": false,
       "ephemeral": true
      },
      "constraints": [
       "user_id=?"
      ]
     }
    }
   ],
   "cte_materializations": [
    {
     "cte_id": 0,
     "name": "spenders",
     "nodes": [
      2
     ]
    }
   ]
  }
 },
 {
  "name": "Coroutine subquery + group by",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON SELECT city_id, avg(age)\nFROM (SELECT * FROM users WHERE age > 18)\nGROUP BY city_id\nORDER BY avg(age);",
   "result_columns": [
    "city_id",
    "avg(age)"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "SCAN (subquery-0)",
     "op": {
      "type": "scan",
      "table": "(subquery-0)",
      "subquery": {
       "execution": "coroutine"
      },
      "source": "subquery"
     }
    },
    {
     "id": 3,
     "parent": 1,
     "detail": "SEARCH users USING INDEX idx_users_age (age>?)",
     "op": {
      "type": "search",
      "table": "users",
      "search_kind": "seek",
      "index": {
       "name": "idx_users_age",
       "covering": false,
       "ephemeral": false
      },
      "constraints": [
       "age>?"
      ]
     }
    },
    {
     "id": 19,
     "parent": null,
     "detail": "USE SORTER FOR GROUP BY",
     "op": {
      "type": "group_by",
      "method": "sorter"
     }
    },
    {
     "id": 61,
     "parent": null,
     "detail": "USE SORTER FOR ORDER BY",
     "op": {
      "type": "order_by",
      "method": "sorter"
     }
    }
   ]
  }
 },
 {
  "name": "UNION with sort",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON SELECT name FROM users WHERE age > 30\nUNION\nSELECT name FROM cities\nORDER BY name;",
   "result_columns": [
    "name"
   ],
   "nodes": [
    {
     "id": 2,
     "parent": null,
     "detail": "COMPOUND QUERY",
     "op": {
      "type": "compound"
     }
    },
    {
     "id": 4,
     "parent": 2,
     "detail": "LEFT-MOST SUBQUERY",
     "op": {
      "type": "compound_arm",
      "op": "left_most",
      "temp_btree": false
     }
    },
    {
     "id": 5,
     "parent": 4,
     "detail": "SEARCH users USING INDEX idx_users_age (age>?)",
     "op": {
      "type": "search",
      "table": "users",
      "search_kind": "seek",
      "index": {
       "name": "idx_users_age",
       "covering": false,
       "ephemeral": false
      },
      "constraints": [
       "age>?"
      ]
     }
    },
    {
     "id": 15,
     "parent": 2,
     "detail": "UNION USING TEMP B-TREE",
     "op": {
      "type": "compound_arm",
      "op": "union",
      "temp_btree": true
     }
    },
    {
     "id": 16,
     "parent": 15,
     "detail": "SCAN cities",
     "op": {
      "type": "scan",
      "table": "cities",
      "source": "table"
     }
    },
    {
     "id": 40,
     "parent": null,
     "detail": "USE SORTER FOR ORDER BY",
     "op": {
      "type": "order_by",
      "method": "sorter"
     }
    }
   ]
  }
 },
 {
  "name": "Correlated + IN subqueries",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON SELECT u.name,\n  (SELECT count(*) FROM orders o WHERE o.user_id = u.id)\nFROM users u\nWHERE u.age IN (SELECT age FROM users WHERE city_id = 3);",
   "result_columns": [
    "name",
    "(SELECT count(*) FROM orders o WHERE o.user_id = u.id)"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "LIST SUBQUERY 1",
     "op": {
      "type": "list_subquery",
      "subquery_id": 1,
      "correlated": false
     }
    },
    {
     "id": 4,
     "parent": 1,
     "detail": "SCAN users",
     "op": {
      "type": "scan",
      "table": "users",
      "source": "table"
     }
    },
    {
     "id": 13,
     "parent": null,
     "detail": "SCAN users AS u",
     "op": {
      "type": "scan",
      "table": "users",
      "alias": "u",
      "source": "table"
     }
    },
    {
     "id": 16,
     "parent": null,
     "detail": "CORRELATED SCALAR SUBQUERY 2",
     "op": {
      "type": "scalar_subquery",
      "subquery_id": 2,
      "correlated": true
     }
    },
    {
     "id": 19,
     "parent": 16,
     "detail": "SEARCH o USING COVERING INDEX idx_orders_user (user_id=?)",
     "op": {
      "type": "search",
      "table": "orders",
      "alias": "o",
      "search_kind": "seek",
      "index": {
       "name": "idx_orders_user",
       "covering": true,
       "ephemeral": false
      },
      "constraints": [
       "user_id=?"
      ]
     }
    }
   ]
  }
 },
 {
  "name": "EXISTS (semi join)",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON SELECT * FROM users u\nWHERE EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id);",
   "result_columns": [
    "id",
    "name",
    "age",
    "city_id"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "SCAN users AS u",
     "op": {
      "type": "scan",
      "table": "users",
      "alias": "u",
      "source": "table"
     }
    },
    {
     "id": 2,
     "parent": null,
     "detail": "SEARCH o USING COVERING INDEX idx_orders_user (user_id=?)",
     "op": {
      "type": "search",
      "table": "orders",
      "alias": "o",
      "join": "semi",
      "search_kind": "seek",
      "index": {
       "name": "idx_orders_user",
       "covering": true,
       "ephemeral": false
      },
      "constraints": [
       "user_id=?"
      ]
     }
    }
   ]
  }
 },
 {
  "name": "Hash join (no usable index)",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON SELECT u.name, s.device\nFROM users u\nJOIN sessions s ON s.session_key = 'sk_' || u.id\nJOIN events e ON e.session_key = s.session_key;",
   "result_columns": [
    "name",
    "device"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "MATERIALIZE hash build input for sessions AS s",
     "op": {
      "type": "hash_build",
      "table": "sessions",
      "alias": "s"
     }
    },
    {
     "id": 3,
     "parent": 1,
     "detail": "HASH JOIN sessions AS s",
     "op": {
      "type": "hash_join",
      "table": "sessions",
      "alias": "s",
      "join": "inner"
     }
    },
    {
     "id": 4,
     "parent": 1,
     "detail": "SCAN users AS u",
     "op": {
      "type": "scan",
      "table": "users",
      "alias": "u",
      "source": "table"
     }
    },
    {
     "id": 53,
     "parent": null,
     "detail": "HASH JOIN events AS e",
     "op": {
      "type": "hash_join",
      "table": "events",
      "alias": "e",
      "join": "inner"
     }
    },
    {
     "id": 54,
     "parent": null,
     "detail": "SCAN users AS u",
     "op": {
      "type": "scan",
      "table": "users",
      "alias": "u",
      "source": "table"
     }
    },
    {
     "id": 55,
     "parent": null,
     "detail": "HASH JOIN sessions AS s",
     "op": {
      "type": "hash_join",
      "table": "sessions",
      "alias": "s",
      "join": "inner"
     }
    }
   ]
  }
 },
 {
  "name": "Multi-index OR",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON SELECT * FROM users WHERE id = 5 OR age = 30;",
   "result_columns": [
    "id",
    "name",
    "age",
    "city_id"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "MULTI-INDEX OR users (PRIMARY KEY, idx_users_age)",
     "op": {
      "type": "multi_index",
      "table": "users",
      "set_op": "or",
      "indexes": [
       "PRIMARY KEY",
       "idx_users_age"
      ]
     }
    }
   ]
  }
 },
 {
  "name": "Recursive CTE",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON WITH RECURSIVE cnt(x) AS (\n  SELECT 1\n  UNION ALL\n  SELECT x + 1 FROM cnt WHERE x < 10\n)\nSELECT x FROM cnt;",
   "result_columns": [
    "x"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "SCAN cnt",
     "op": {
      "type": "scan",
      "table": "cnt",
      "subquery": {
       "execution": "coroutine",
       "cte_id": 0,
       "recursive": true
      },
      "source": "subquery"
     }
    },
    {
     "id": 5,
     "parent": 1,
     "detail": "SETUP",
     "op": {
      "type": "recursive_setup"
     }
    },
    {
     "id": 6,
     "parent": 5,
     "detail": "SCAN CONSTANT ROW",
     "op": {
      "type": "constant_row"
     }
    },
    {
     "id": 17,
     "parent": 1,
     "detail": "RECURSIVE STEP",
     "op": {
      "type": "recursive_step"
     }
    },
    {
     "id": 18,
     "parent": 17,
     "detail": "SCAN cnt",
     "op": {
      "type": "scan",
      "table": "cnt",
      "source": "recursive_cte_input"
     }
    }
   ]
  }
 },
 {
  "name": "Window function",
  "plan": {
   "version": 1,
   "sql": "EXPLAIN QUERY PLAN FORMAT=JSON SELECT name,\n  row_number() OVER (PARTITION BY city_id ORDER BY age)\nFROM users;",
   "result_columns": [
    "name",
    "row_number() OVER (PARTITION BY city_id ORDER BY age)"
   ],
   "nodes": [
    {
     "id": 1,
     "parent": null,
     "detail": "SCAN window_subquery_0",
     "op": {
      "type": "scan",
      "table": "window_subquery_0",
      "subquery": {
       "execution": "coroutine"
      },
      "source": "subquery"
     }
    },
    {
     "id": 3,
     "parent": 1,
     "detail": "SCAN users",
     "op": {
      "type": "scan",
      "table": "users",
      "source": "table"
     }
    },
    {
     "id": 13,
     "parent": 1,
     "detail": "USE SORTER FOR ORDER BY",
     "op": {
      "type": "order_by",
      "method": "sorter"
     }
    }
   ]
  }
 }
];
